### PR TITLE
feat(image): Add ubuntu 20.04 image

### LINKED ISSUE #248: Image for Ubuntu 20.04

### PR DESCRIPTION
**Pull request by sayboras**
This PR is to add ubuntu 20.04 image.
Dockerfile is copied from 18.04.

Closes #248

Signed-off-by: Tam Mach <sayboras@yahoo.com>

### CODE REVIEW

**Review by chanwit — APPROVED** [review]
LGTM

Thank you @sayboras for your contribution!

**Comment by sayboras** [comment]
Build failed, it seems unrelated to changes, but more about gorelease version/config.

```
         • optimistically guessing `brew[0].installs`, double check
            • DEPRECATED: `brews.github` should not be used anymore, check https://goreleaser.com/deprecations#brewsgithub for more info.
      • scoop manifests  
      • milestones       
   ⨯ command failed            error=config is valid, but uses deprecated properties, check logs above for details
```

**Comment by sayboras** [comment]
Above issue should be fixed in https://github.com/weaveworks/footloose/pull/253

**Comment by chanwit** [comment]
A quick rebase to master would be make it green :-)
Thank you for both fixes.

**Comment by sayboras** [comment]
> A quick rebase to master would be make it green :-)
> Thank you for both fixes.

I just did a rebase.

The talk from kube conf leads me here. Footloose is awesome for creating light weight VM-like machines. Thanks :100:

**Comment by chanwit** [comment]
Glad you love it. Cheers!

**Comment by chanwit** [comment]
Merged. Congrats @sayboras!!

**Pull request merged**
