### PR TITLE
Update: footloose serve

### PR DESCRIPTION
**Pull request by till**
While playing around, I added a few things.

##  made `serve` more talkative
   - added logger
     - to show it started, etc. (with the options provided)
     - in debug: it shows route matched
   - added --debug flag (which enables a little more output)

image

## api docs

 - added really simple "API docs"
 - all based on routes and methods for now

image

### CODE REVIEW

**Comment by chanwit** [comment]
@till could you please re-check your goreleaser patch again? it broke this build.

**Comment by till** [comment]
@chanwit I think I broke it in different ways, I'll have a look and rebase.

**Comment by till** [comment]
@chanwit I had broken the tests with `debug` and also cleaned up my api docs method, and my usage of mux. I think nothing else looked broken or needed fixing.

**Comment by chanwit** [comment]
@till I see. Sorry for spotting the wrong one :-(

This change LGTM

**Comment by chanwit** [comment]
Thank you very much for your contribution, @till :tada: :tada: :tada:

**Pull request merged**
