### PR TITLE
Add clearlinux docker image

### PR DESCRIPTION
**Pull request by ganeshmaharaj**
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>

### CODE REVIEW

**Comment by dlespiau** [comment]
Hi Ganesh!

Thanks for taking the time to contribute to `footloose`!

The tests are currently failing when checking the image contains a set of tools we are trying to enforce across our base images. At the moment, we require:

```
footloose --config %testName.footloose ssh root@node0 hostname
footloose --config %testName.footloose ssh root@node0 ps
footloose --config %testName.footloose ssh root@node0 ifconfig
footloose --config %testName.footloose ssh root@node0 ip route
footloose --config %testName.footloose ssh root@node0 -- netstat -n -l
footloose --config %testName.footloose ssh root@node0 -- ping -V
footloose --config %testName.footloose ssh root@node0 -- curl --version
footloose --config %testName.footloose ssh root@node0 -- wget --version
footloose --config %testName.footloose ssh root@node0 -- vi --help
```

**Comment by ganeshmaharaj** [comment]
@dlespiau I missed that part on the first round, but quickly realized i missed those. ClearLinux provides all those packages across the 3 bundles and the host image. https://github.com/weaveworks/footloose/pull/135/files#diff-478270ff04404e997657e0d2ed87e803R5 should cover them all. The recent test failure seems to be a timeout after waiting for 10m by travis. 
https://travis-ci.org/weaveworks/footloose/builds/518129670#L5322-L5323 

Just to be sure, I just checked the container image with those commands and they all exist.

**Comment by mcastelino** [comment]
@ganeshmaharaj it may make sense to have a footloose specific bundle in Clear. That will allow Clear to be setup to be optimal with footloose.

/cc @bryteise

**Comment by dlespiau** [comment]
I just re-triggered the CI run, it seems to have timed out on downloading something yesterday. All good now!

**Comment by dlespiau** [comment]
Thanks a lot for your contribution, merging!

**Pull request merged**
