### PR TITLE
Display left aligned #115

### LINKED ISSUE #115: show: A few tweaks on the table view
Compare:

```$ footloose show 
       NAME       HOSTNAME    PORTS                 IMAGE                   CMD       STATE   

  /cluster-node1  node1     22->33031  quay.io/footloose/centos7:latest  /sbin/init  Stopped  
  /cluster-node0  node0     22->33030  quay.io/footloose/centos7:latest  /sbin/init  Stopped  
```
With
```
$ docker ps
CONTAINER ID        IMAGE                              COMMAND             CREATED             STATUS              PORTS                   NAMES
79821fa69596        quay.io/footloose/centos7:latest   "/sbin/init"        31 minutes ago      Up 31 minutes       0.0.0.0:33031->22/tcp   cluster-node1
4e5f25cb6321        quay.io/footloose/centos7:latest   "/sbin/init"        31 minutes ago      Up 31 minutes       0.0.0.0:33030->22/tcp   cluster-node0
```

Headers should be left aligned and no space between the first value (`  /cluster-node1`).

### PR DESCRIPTION
**Pull request by u5surf**
update #115 

- [o ] Headers should be left aligned 
- [x ] no space between the first value

### CODE REVIEW

**Comment by dlespiau** [comment]
It sems like travis is going a bit slow today, the tests usually run in ~12 mins to run but they are still going on. Oh well :)

**Comment by Skarlso** [comment]
Need to fix the test. :)

**Comment by dlespiau** [comment]
@u5surf we could merge this partial fix if you wish. Or do you want to look at the other part too?

**Comment by u5surf** [comment]
I’m willing not to look anything. I cannot be removed the space in first value. Because it’s the matter of the tablewriter library.

**Comment by dlespiau** [comment]
Ah, ok, thanks for telling us! We may need to change the library if that's not possible.

But for now, thanks a lot for looking at this and your first contribution! merging your PR!

**Pull request merged**
